### ISSUE TITLE
Model In-game Bug

### ISSUE THREAD

**Issue by LiamVallance** [SplashAttackOnUnity/Splash_Attack#3]
Currently when you play the game either in engine or through .exe the white model built in the scene view is there and a second blue model spawns in that is controllable:

![capture](https://cloud.githubusercontent.com/assets/10143803/26000760/168c0dc2-3722-11e7-9067-0c72ffdf0351.PNG)
![screenshot](https://cloud.githubusercontent.com/assets/10143803/26000766/19f005e0-3722-11e7-8d94-93f84583b2e2.png)

This should be a simple fix but thought i would put this up anyways

**Comment by 14016036** [comment]
oh this actually isn't a bug.. basically in the higharchy tab is where you actually like customize/edit prelabs.. and you move it down to the "project" part when you want it to be a prelab/update the prelab with the latest updates.. when I was making the camera movement with the mouse and clamping it, i never removed the player gameobject that i was editing outta the prelab becus i was using that to test at which point was the clamp stopping my camera angle.

**Comment by LiamVallance** [comment]
Ah right that makes sense, i get it
