### ISSUE TITLE
Player jump

### ISSUE THREAD

**Issue by 14016036** [SplashAttackOnUnity/Splash_Attack#6]
Okey, so after a stupid amount of time to do a simple thing i've finally added a jump mechanic to the character that is capable of jumping... unfortunately there was only two ways of doing this.. adding a Character Controller component (starting to think this woulda been easier) or a rigidbody component considering we'll be needing rigidbody i felt it best to write the code that way.. 

Now the problems:

1. Currently for some unknown reason when you look in specific angles with the character model it fucks up the rigidbody and it goes completely berserk which is why i originally removed the component from the character model (obviously since i've added it, this needs to get fixed some how)

2. Because we haven't got a level set up or anything (I suggest we find one online that we can use as a dev custom level to obviously test stuff) I haven't created a raycast to do checks to see if the character is in the air or not.. this is a really simple implementation that shouldn't take me very long to add when we have a level that i can throw one on, so at the moment the character can jump while in the air.

I created the jump force as a public variable so you don't have to go into the script to edit it you can do it via the playercontroller script component on unity if you fancy playing around with it.. or you can simply look at the script itself to see how I've written it. 

p.s. I was meant to only put this on the PlayerController branch but for some reason I was on the Master and it refused to let me checkout until I updated the master with the current stuff that i had done, so i did that switched to Playercontroller then officially updated to that, so make sure you git pull from the master (or playercontroller) to get this update seeing as both of them are completely up to date with one another.

**Comment by 14016036** [comment]
Okey. so did some more work on the jump ability today so let me run down what exactly I've done.

so originally I thought i'd need a raycast to prevent the player from making a double jump but i found a somewhat easier way, so what i did was I added a sphere collider to the player and made it a trigger.

Then I created a new tag and had the floor (which i remade) tagged as "floor" to make things simple, by doing it this way it makes reusing the code really simple, lets say you wanted to add a ramp to the floor already normally the jump script would not work on the ramp because it doesn't understand it. but if you create the ramp now and assign the tag to the ramp "floor" the code will work on that ramp as if it was actually the floor. 

now in the script I created two triggers a enter one and an exist and in these triggers I just check to see if the player collides with an object that has the tag "floor" and if it does, either set a bool canJump to true or false, I then obviously edited the jump function so it can only jump if the canJump == true.

another thing I also added was gravity phsyics to the player so jumping looks more realistic and doesn't have this "floaty" feel to the jumps.

Now on to the issues.. with the problem we have with the rigidbody being an issue this has also become an issue with the detection of the triggers (I had a feeling it would do) and sometimes it doesn't detect that the player is colliding with the floor so canJump can = false even when it shouldn't be.

**Comment by LiamVallance** [comment]
Fair play that is some amazing work you have done there, I am away for a few days at the moment but when I get home I will have to trial it and get a feel for how it works, seriously though, good work

**Comment by 14016036** [comment]
Okey... so after playing around with it I've noticed there are some bugs.. e.g sometimes if you jump while holding a button to move at an angle it'll get stuck and you'll only be able to jump when pushing that button down, other times it does some variation on this bug.. will look into it. but i'm honestly not sure would could be causing this issue especially considering i just rewrote the movement code, so it cannot be that.

**Comment by 14016036** [comment]
-fixed (not tested incredibly thoroughly)
