### ISSUE TITLE
Flag & player colliding with flag

### ISSUE THREAD

**Issue by 14016036** [SplashAttackOnUnity/Splash_Attack#9]
Okey, so i've added a flag into the game that the player is able to collide with, once the player has collided with the flag, it then attaches to the player on its back... unfortunately when the flag gets attached to the player we bring that old bug where the player goes berserk when looking in specific angles... i have a funny feeling i know what is causing the issue but i don't know why its causing it.

**Comment by LiamVallance** [comment]
Have you tried using tag collision so that only if an object of say tag "player" collides with an object of tag "flag" then collide, in theory if "flag" collides with "floor" then nothing should happen and maybe then there will be no problem?

**Comment by 14016036** [comment]
that's how i've set my code up. i have a sneaky feeling it still has something to do with the first person camera code.. cus this issue only ever seems to be a problem when you have a physical child GameObject as a child object of the player GameObject..

**Comment by 14016036** [comment]
-fixed (for now knowing my luck)
